export const FONTS = [
  { label: 'Default font', value: '' },
  { label: 'Sourc a ans', value: 'SourceHanSans' },
  { label: 'Sourc a erif', value: 'SourceHanSerif' },
  { label: 'We in LKa i', value: 'WenDingPLKaiTi' },
  { label: 'We in LSon i', value: 'WenDingPLSongTi' },
  { label: 'Zhuqu an ong', value: 'ZhuqueFangSong' },
  { label: 'LXGWWe ai', value: 'LXGWWenKai' },
  { label: 'Alibab  u i', value: 'AlibabaPuHuiTi' },
  { label: 'M ans', value: 'MiSans' },
  { label: 'D  ei', value: 'DeYiHei' },
  { label: 'Cange iaowanzi', value: 'CangerXiaowanzi' },
  { label: 'Yoush itl lack', value: 'YousheTitleBlack' },
  { label: 'Fengguan ingrui', value: 'FengguangMingrui' },
  { label: 'Shet oder quare', value: 'ShetuModernSquare' },
  { label: 'Zcoo appy', value: 'ZcoolHappy' },
  { label: 'Zizh   ai', value: 'ZizhiQuXiMai' },
  { label: 'Suca ish angkang', value: 'SucaiJishiKangkang' },
  { label: 'Suca ish oo quare', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuni ounded', value: 'TuniuRounded' },
  { label: 'Ruiz henyan', value: 'RuiziZhenyan' },
  { label: 'Sourc erif4', value: 'SourceSerif4' },
  { label: 'Je rain ono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Ope ans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Sourc an ro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
]